const menu = [
    {
      id: 1,
      title: 'buttermilk pancakes',
      category: 'breakfast',
      price: 15.99,
      img:  '/images/pasta.jpg',
      desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle `,
    },
    {
      id: 2,
      title: 'diner double',
      category: 'lunch',
      price: 13.99,
      img: '/images/dosa.jpg',
      desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings `,
    },
    {
      id: 3,
      title: 'godzilla milkshake',
      category: 'shakes',
      price: 6.99,
      img: '/images/maggi.jpg',
      desc: `ombucha chillwave fanny pack 3 wolf moon street art photo booth `,
    },
    {
      id: 4,
      title: 'country delight',
      category: 'breakfast',
      price: 20.99,
      img: '/images/pasta.jpg',
      desc: `Shabby chic keffiyeh neutra snackwave pork belly shoreditch.  `,
    },
    {
      id: 5,
      title: 'egg attack',
      category: 'lunch',
      price: 22.99,
      img: '/images/dosa.jpg',
      desc: `franzen vegan pabst bicycle rights kickstarter pinterest  `,
    },
    {
      id: 6,
      title: 'oreo dream',
      category: 'shakes',
      price: 18.99,
      img: '/images/maggi.jpg',
      desc: `Portland chicharrones ethical edison bulb, palo santo craft `,
    },
    {
      id: 7,
      title: 'bacon overflow',
      category: 'breakfast',
      price: 8.99,
      img:  '/images/pasta.jpg',
      desc: `carry jianbing normcore freegan. Viral single-origin coffee live-edge `,
    },
    {
      id: 8,
      title: 'american classic',
      category: 'lunch',
      price: 12.99,
      img: '/images/dosa.jpg',
      desc: `on it tumblr kickstarter thundercats migas everyday carry `,
    },
    {
      id: 9,
      title: 'quarantine buddy',
      category: 'shakes',
      price: 16.99,
      img: '/images/maggi.jpg',
      desc: `skateboard fam synth authentic semiotics. Live-edge lyft `,
    },
  ];
  export default menu;
  